Metaswitch/clearwater-snmp-handlers

Makefile, ut/coverage-not-yet
Alex, can you review these changes to tidy up the Makefile a bit
=> [Reviewer: Alex] Tidy up makefile

zmq_message_handler.cpp
Graeme,
Please can you review this change, which fixes #49?
I've live-tested.
Matt
=> [Reviewer: Graeme] Check we have sufficient statistics on 0MQ interface before exposing over SNMP

PROJECT-CLEARWATER-MIB, homesteaddata.cpp
Matt, can you review the updated snmp handlers with the new Diameter routing stats
=> [Reviewer: Matt] Update stats

.gitignore, Makefile, mk/platform.mk
Revamp the Makefile to fix #41 and #21.
Full disclosure, also includes a new (better) model for handling `.d` files which we should apply elsewhere if you're happy with the principle.
=> Reviewer Rob - Tidy up makefile

PROJECT-CLEARWATER-MIB
=> Remove bad quotes

alarm_req_listener.cpp, ut/alarm_req_listener_test.cpp
Fixes the hang we're seeing on the repo server.
=> [Reviewer: Andy] Set a ZMQ_LINGER option so we quit when told to

alarms_agent.cpp
Tested live, by setting it to two IPs and confirming that alarms were sent to both. Fixes #70.
=> [Reviewer: Ellie] Allow snmp_ip to be a comma-separated list

Makefile, alarm_table_defs.cpp, alarm_table_defs.hpp, alarms_agent.cpp, ut/alarm_req_listener_test.cpp, ut/alarm_table_defs_test.cpp, ut/clear_missing/clear_missing.json, ut/desc_too_long/desc_too_long.json, ut/details_too_long/details_too_long.json, ut/invalid_cause/invalid_cause.json, ut/invalid_json/invalid_json.json, ut/invalid_json_format/invalid_json_format.json, ut/invalid_severity/invalid_severity.json, ut/multi_definition/multi_definition.json, ut/non_clear_missing/non_clear_missing.json, ut/valid_alarms/valid_alarms.json
Rob, can you please review this change to have the alarms agent parse its alarms from JSON files, not cpp-common. This also holds the UTs for the common alarm parsing code.
=> [Reviewer: Rob] Parse from multiple files

alarm_req_listener.cpp, alarms_agent.cpp
Rob, can you review these fixes for the alarms agent. The main fix is that we didn't check the output of running start on the AlarmReqListener, so we could run a broken process
Tested live
Fixes #78, fixes #77, fixes #76
=> [Reviewer: Rob] SNMP fixes

PROJECT-CLEARWATER-MIB
Updated to MIB file for Chronos total timers count
=> [Reviewer: Matt] Updated MIB file for Chronos total timers count

debian/clearwater-snmp-alarm-agent.postrm
Similar changes to https://github.com/Metaswitch/ralf/pull/174
=> [No reviewer] Postrm fix

PROJECT-CLEARWATER-MIB
MIBMIBMIB
Really nothing controversial. Unsigned32 seems to work on brief live tests. will test further tomorrow. 
Passes smilint without error.
=> [Reviewer: Andy] MIB with u32 changes in

debian/control
Doug, I've taken your proposed fix for #104, can you please review?
=> Reviewer Doug - alarm-agent replaces handler-alarm

alarm_req_listener.cpp
Fixes https://github.com/Metaswitch/clearwater-etcd/issues/214
=> [Reviewer: Rob] iss214: Adds comment explaning alarm state->severity mapping

Makefile, alarm_active_table.cpp, alarm_model_table.cpp, alarm_model_table.hpp, alarm_table_defs.cpp, alarm_table_defs.hpp, alarms_agent.cpp, docs/Testing.md, fvtest.conf, fvtest.supp, itu_alarm_table.cpp, itu_alarm_table.hpp, ut/alarm_tables_testing.cpp, ut/alarm_tables_testing.hpp
Also see changes made in cpp-common:
https://github.com/Metaswitch/cpp-common/pull/438
=> [Reviewer: Rob] Creates a custom alarm definition

PROJECT-CLEARWATER-MIB
Add entries for new stats, and re-arrange chronos entries
=> [No Reviewer] Update MIB for chronos API changes

Makefile
=> [No reviewer] Fix 'make deb' failure

src/ut/alarm_tables_testing.cpp
Co-req change to go along with https://github.com/Metaswitch/cpp-common/commit/13484983824159cf2b6fe78ad1a50de136fe7fec
=> [No review required] Make the alarm agent UTs work on centos

Makefile, clearwater-snmp-alarm-agent.root/usr/share/clearwater/bin/clearwater-snmp-alarm-agent-wrapper, debian/clearwater-snmp-alarm-agent.service, debian/clearwater-snmp-alarm-agent.upstart, rpm/.gitignore, rpm/clearwater-snmp-alarm-agent.spec
Hi Matt, 
Another PR, this time porting the alarm agent to centos. Again, I've tested that the RPM builds successfully, but I've not done any live testing yet. 
Thanks,
Alex.
=> [Reviewer: Matt] Port the alarm agent to Centos

debian/clearwater-snmp-alarm-agent.service
Similar to https://github.com/Metaswitch/clearwater-monit/pull/34
=> [No reviewer] Have process restart set to always, to cover when PID is killed

rpm/clearwater-snmp-alarm-agent.spec
Update to use new el7_2 versioned net-snmp
=> [No Reviewer] Update net-snmp dependencies

PROJECT-CLEARWATER-MIB
Co-req change to https://github.com/Metaswitch/sprout/pull/1519.
=> [Reviewer: Adam] Add ringing time statistic

PROJECT-CLEARWATER-MIB
Add the three stats for shared/default IFCs
=> [Reviewer: Krista] Add the IFC stats

PROJECT-CLEARWATER-MIB
Add the stat from Metaswitch/sprout#1840
=> [Reviewer: KH1] Add stat for call barring

mib-generator/CLEARWATER-MIB-COMMON, mib-generator/CLEARWATER-MIB-PC-EXTRAS
I'm not actually going to merge into the automated-mib-build-infra branch, but setting the PR up this way shows the relevant changes...
=> Update terminology for split state

mib-generator/CLEARWATER-MIB-COMMON
This changes any instance of IFC -> iFC.
=> [No reviewer] Use iFC consistently

mib-generator/CLEARWATER-MIB-COMMON
Adding Bifrost MIB references to the standard location to allow for auto-generation of documentation.
=> Added Bifrost MIB to Common MIB

clearwater-snmp-alarm-agent.root/usr/share/clearwater/bin/show_active_alarms, debian/clearwater-snmp-alarm-agent.links
As discussed - I think you've already tested this live on a node, so we just need a command to invoke it.
=> [Reviewer: Rob] Add command to show active alarms

mib-generator/CLEARWATER-MIB-COMMON
Fix up capitalization errors in MIB
=> [No reviewer] Fix MIB

src/ut/alarm_scheduler_test.cpp
We previously used `_alarm_scheduler->_cond->signal();` without first taking the AlarmScheduler's lock. This left a window where the handler thread could be currently processing and not waiting when we signalled it, which meant that it missed the signal.
I've tested this by adding in sleep statements for force us to hit this window, verified the test failed and then added the locking and verified it now passes.
This fixes: https://github.com/Metaswitch/clearwater-issues/issues/2354
`make full_test` still passes
=> [Reviewer: Richard] Fix window condition in UTs that caused intermittent failure

mib-generator/CLEARWATER-MIB-COMMON, mib-generator/CLEARWATER-MIB-PC-EXTRAS
Companion PR to Metaswitch/sprout#2010
=> [Reviewer: KH1] Add table for worker thread queue success/failure

src/Makefile
Seb,
Please can you review this fix to cw_alarm_fvtest?  I've tested on my dev box and it passes.
Thanks,
Matt
=> [Reviewer: Seb] Fix cw_alarm_fvtest build

METASWITCH-OS-MIB
This is the ASN.1 definition - I've run it through an online validator and it seems to be syntactically correct.
=> [Reviewer: Adam] File descriptor MIB addition

mib-generator/CLEARWATER-MIB-COMMON
Changes for [#2066](https://github.com/Metaswitch/sprout/pull/2066).
=> [Reviewer: AJH] Locality Optimization
