Metaswitch/clearwater-snmp-handlers

astairedata.cpp
Graeme,
Please can you review this change, which fixes #48?  I spotted it while investigating homestead's MIB handlers crashing (a fix for which is to follow shortly).
I've live-tested.
Matt
=> [Reviewer: Graeme] Add .0 to Astaire's scalar statistic OIDs

zmq_message_handler.cpp
Tested by patching a sprout node (on which the "snmp" package has been installed, and the OID tables uploaded to enable reporting of textual OIDs) and then running the command 
snmpwalk -v2c -c clearwater localhost .1.2.826.0.1.1578918.9.3.3.1
to fetch the contents of sproutConnectedHomesteadsTable.  
This returned output in the expected format, namely
PROJECT-CLEARWATER-MIB::sproutHomesteadConnectionCount.ipv4."<homestead IP>" = ....
and not (erroneously)
PROJECT-CLEARWATER-MIB::sproutConnectedHomesteadsEntry.ipv6z.<homestead IP> = ...
as this test did previously
=> Reviewer AMC: Add Entry and ConnectionCount elements to OIDs

Makefile
Recent changes meant we were always passing `-fPIC` to the linker, which meant that UT code couldn't' link (as the compiles are done without `-fPIC`).  This makes us pass the flag only where we need to.
UTs now build and run happily.
=> Reviewer Alex - Don't pass -fPIC to UT builds

PROJECT-CLEARWATER-MIB
Corresponding changes to https://github.com/Metaswitch/cpp-common/pull/311.
* My new code exposes three scopes for time-based tables (prev 5 seconds, current 5 minutes, prev 5 minutes) so I could make sure my code was sufficiently flexible. I've now updated this to match.
* I also took the opportunity to correct `scopeCurrent5SecondPeriod` to `scopePrevious5SecondPeriod` (which I think we agreed was more accurate even for existing stats).
* I noticed that there were some references to "hss" which should have been "homestead", so I've fixed those up.
=> [Reviewer: Matt] Scope changes

custom_handler.cpp
Bug here is that if you issue an SNMP GET to a node specifying mulitple OIDs, you get the value of the first reported for all of them.
Fix tested live using snmpget with mulitple OIDs
=> Review AMC: Don't report the same value if SNMP GET performed for multiple OIDs

PROJECT-CLEARWATER-MIB
Can you review this fix, to make `smilint ./PROJECT-CLEARWATER-MIB -l 5` run cleanly?
It:
* fixes up some rogue commas
* doesn't list inaccessible objects in astaireGroup
* reworks the AstaireConnectionBucketBandwidthTable, following the guidance in http://stackoverflow.com/questions/2510211/snmp-asn-1-mib-definitions-referencing-a-table-within-a-table that nested tables should just be indexed by the parent table's index as well as their own
I'll also change Jenkins to run that smilint command and fail the build if it fails.
=> [Reviewer: Andy] Fix up smilint warnings

debian/clearwater-snmp-alarm-agent.postinst, debian/clearwater-snmp-alarm-agent.postrm, debian/clearwater-snmp-handler-astaire.postinst, debian/clearwater-snmp-handler-astaire.postrm, debian/postinst, debian/postrm, debian/rules
Matt, can you review these changes to keep the alarm agent and snmp under monit's control. 
Tested by installing and checking that nothing obviously broke
Part of the fix for #98
=> [Reviewer: Matt] Control the alarm agent and snmpd through monit

Makefile, alarm_model_table.cpp, alarm_req_listener.cpp, alarm_table_defs.cpp, alarm_trap_sender.cpp, alarms_agent.cpp, debian/clearwater-snmp-alarm-agent.init.d
Part of the fix to https://github.com/Metaswitch/clearwater-snmp-handlers/issues/91.
This:
- logs to a file (/var/log/clearwater-alarms/clearwater-alarms_20151028T180000Z.txt) instead of syslog
- uses our (newish) standard SNMP setup code from cpp-common
- adds a log on each trap sent, for historical diagnostic purposes
I've tested that I get sensible logs out:
```
28-10-2015 18:39:43.361 UTC Warning alarm_trap_sender.cpp:222: Trap with alarm ID 1500.6 being sent
28-10-2015 18:39:55.017 UTC Warning alarm_trap_sender.cpp:222: Trap with alarm ID 1500.1 being sent
28-10-2015 18:40:53.825 UTC Warning alarm_trap_sender.cpp:222: Trap with alarm ID 1500.6 being sent
```
I will test that:
- alarms go out on the wire when snmp_ip is set
- alarms don't go out on the wire, and no errors are logged, …
=> [Reviewer: Alex] Use common logging and SNMP infrastructure, and log on each alarm

clearwater-snmp-alarm-agent.root/usr/share/clearwater/infrastructure/scripts/restart/clearwater_snmp_alarm_agent_restart, debian/clearwater-snmp-alarm-agent.postinst, debian/rules
Purge some monit infrastructure that wasn't included in https://github.com/Metaswitch/clearwater-snmp-handlers/pull/102.
Tested live - the alarm agent is now actually running after install.
=> [Reviewer: Andy] Ensure upstart actually starts the alarm agent

alarm_req_listener.cpp, alarm_req_listener.hpp, alarms_agent.cpp, debian/clearwater-snmp-alarm-agent.postinst, debian/clearwater-snmp-alarm-agent.upstart, ut/alarm_req_listener_test.cpp
- create the /var/run/clearwater directory
- catch zmq_bind failures before starting the listener thread
- fire the termination semaphore when the listener thread exits
This doesn't fully implement Monit polling of the alarm agent, but does add a 'poll' message to the list of ZMQ messages we'll accept.
=> [Reviewer: Ellie] Fixes for issue #96

debian/clearwater-snmp-alarm-agent.postinst, debian/clearwater-snmp-alarm-agent.triggers
Andy, can you review this change to add a trigger to the alarm agent to restart it? This PR adds the restart function, and makes the clearwater-snmp-alarm-agent interested in the alarm agent trigger
=> [Reviewer: Andy] Add a trigger to restart the alarm agent

.gitignore, alarm_req_listener.cpp
Fix up coverage for clearwater-snmp-handlers (Jenkins wasn't running coverage tests - it is now)
=> [No reviewer] Fix up coverage

alarm_trap_sender.cpp, ut/alarm_req_listener_test.cpp
As we discussed, the trap sender now sends all alarms it knows about, set or cleared. 
As there is no longer a clear_all method for alarms, I am removing the UT for it.
=> [Reviewer: Rob] Remove clear all alarms

alarm_req_listener.cpp, alarm_trap_sender.cpp, alarm_trap_sender.hpp
The clear_alarms functionality is no longer going to be used. 
The calls to `clear_all` have been removed already from all modules, and the function will be removed from cpp_common Alarms class shortly.
Removing it from snmp-handlers. This will fix the coverage failure.
=> [No Reviewer] Remove clear_alarms

Makefile, alarm_table_defs.cpp, alarm_table_defs.hpp, alarm_trap_sender.cpp, alarm_trap_sender.hpp, debian/control, ut/alarm_req_listener_test.cpp, ut/fakenetsnmp.cpp, ut/fakenetsnmp.h
Registers for callbacks when sending SNMP alarms and, if the send failed **and** the alarm is still active, resend the TRAP.
The only slight nasty is that I have to clone the `AlarmTableDef` object to use as the alarm correlator, which then gets cleaned up after the callback pops.  You'll see in the UTs I've added a utility function that sorts this out in the tests if all they need is for the alarm to succeed.
=> Reviewer Rob - Use SNMP NOTIFY callbacks to re-send unacknowledged alarms

alarm_active_table.cpp, ut/alarm_tables_testing.cpp
This fixes up a couple of compiler warnings I saw when compiling with a newer compiler (Clang 3.8):
* preferring std::abs to abs when getting absolute values (http://stackoverflow.com/questions/21392627/abs-vs-stdabs-what-does-the-reference-say)
* explicitly marking integer literals as unsigned, if we're comparing them to unsigned values
=> [Reviewer: Andrew] Fix up warnings when compiling with clang

Makefile, alarm_req_listener.cpp
Previously, these UTs had to be run as root (at least once) because they needed to create /var/run/clearwater. This changes the alarm location we use in UT to a file in /tmp, so that it doesn't need to run as root.
=> [Reviewer: Andrew] Allow running UT without /var/run/clearwater

debian/.gitignore, include/alarm_trap_sender.hpp, src/alarm_trap_sender.cpp
Alex, Andrew,
Please can you review my fix to get alarm (INFORM) resending?  I've tested live, but I don't have a server that will respond positively to INFORMs, so I haven't seen the non-resend behavior - Andrew, I think you said you'd be OK to test this as part of your testing.
There are three changes here.
*   We can't get access to the peer IP address.  Rather than enhancing net-snmp to plumb this through, I've just removed the trace statements (which were the only use).
*   We cloned the AlarmTableDef to pass to net-snmp, but since the AlarmTableDefs are all persistent anyway, I think we can just pass the actual pointer to it.  This means we don't have to worry about when to delete the copy (which is far from trivial to determine).
*   (The .gitignore change is just a tidy-up.) …
=> [Reviewer: Alex, Andrew] Fix alarm resend

debian/clearwater-snmp-alarm-agent.service
Small fix to put to the clearwater-snmp-alarm-agent.service unit file (one of the values was in the wrong section).
I've tested live by running `sudo systemctl daemon-reload` to reload systemd's config. Before the change I got the following in /var/log/messages, now messages is clean. 
```
Jun 30 13:49:47 ip-10-0-7-154 systemd: [/etc/systemd/system/clearwater-snmp-alarm-agent.service:12] Unknown lvalue 'Before' in section 'Install'
```
=> [Reviewer: Matt] Put the monit Before directive in the right place

clearwater-snmp-alarm-agent.root/usr/share/clearwater/install/triggers/clearwater-snmp-alarm-agent, debian/clearwater-snmp-alarm-agent.postinst
Hi Matt, please can you review this PR to rework the alarm agent's triggers.
The PR makes two changes: 
* Refactors the processing that is involved when the agent is triggered into a separate script which can be called directly. This is needed on centos which has a less rich triggering infrastructure. 
* Makes the triggering logic work on ubuntu and centos. 
This means that packages which want to trigger the alarm agent can either call the script directly, or use the existing debian triggering mechanism (which maps through to the script). This means we don't have to go through all our debian packages and change them immediately; we can do this as we port them to work on centos. I don't think this technical debt will cost us very much.
I've tested live with:
* A centos package that calls …
=> [Reviewer: Matt] Triggers rework

include/alarm_scheduler.hpp, src/alarm_scheduler.cpp, src/ut/alarm_scheduler_test.cpp
Use a mock cond var to fix up a case where we couldn't guarantee full coverage
=> [No reviewer] Fix up intermittent coverage

PROJECT-CLEARWATER-MIB
This is the equivalent MIB update corresponding to metaswitch/sprout#1638
=> [REVIEWER: Ellie] Add a stat to track forked INVITEs due to multiple bindings

CLEARWATER-ENTERPRISE-MIB, clearwater-snmp-alarm-agent.root/usr/share/clearwater/bin/clearwater-snmp-alarm-agent-wrapper, include/alarm_scheduler.hpp, include/alarm_trap_sender.hpp, src/alarm_scheduler.cpp, src/alarm_trap_sender.cpp, src/alarms_agent.cpp
I suspected that https://github.com/Metaswitch/clearwater-snmp-handlers/issues/170 might be debatable as a product issue, but it makes it much easier for us to centrally manage and monitor alarms on our test systems, so I've added it.
While I was in the area, I fixed the --local_ip option to use dashes like the other options.
I'll test live once reviewed (and before merging), by installing this on a system and checking its hostname shows up in the alarm.
=> [Reviewer: Ellie] Set hostname in enterprise alarms

PROJECT-CLEARWATER-MIB
Some SCSCF specific stats didn't previously have SCSCF in their name -- this PR renames them for consistency with other such stats.
Some SIP transactions are not in fact tracked by the various sprout[XXX][Incoming/Outgoing]SIPTransactions tables.  This PR updates the stat descriptions to clarify this.
=> [Reviewer: Adam] Clarify and rename some transaction stats

PROJECT-CLEARWATER-MIB
@AME2, assigned to you as you wrote the bits of the descriptions that I propose to change here. This is very minor, and not urgent. If you aren't the right person, please reassign.
The previous description for these stats was not quite as clear as it could be. This very small tweak aims to improve both.
Specifically, the change is from:
"Reported in units of tens of thousands of a percent. When there are zero attempts made the value will..."
To (with changes bolded):
"Reported in units of **ten thousandths** of a percent. When there are zero attempts **made,** the value will..."
=> [Reviewer: AME2] Improve descriptions for success percentage

PROJECT-CLEARWATER-MIB
Assigned to @MatMeredith as the recommended reviewer - if you're not the right person, please pass it on.
It initially seems counter-intuitive that we log 3xx responses as a 'failure', given that they can lead to redirection and call success. After discussion and thinking, we decided to keep logging 3xx as a failure, but also to clarify the table descriptions to make explicitly clear that 3xx responses are logged as failures - this reduces the potential for confusion if an operator expects a significant number of 3xx responses to pass through the network.
=> [Reviewer: MGM] Added clarification to transaction tables that 3xx is counted as failure

PROJECT-CLEARWATER-MIB
This was spotted. Very minor change to correct missing spaces, so I'm merging in without a review.
=> [No reviewer] Add in missing spaces to PROJECT-CLEARWATER-MIB

CLEARWATER-ENTERPRISE-MIB, src/alarm_trap_sender.cpp
Hi Ellie
Can you sign off on this change for me (we discussed last week)?  I've also tweaked the MIB text to make it clear that the OID is for the alarm itself, not the alarmed object (which wouldn't have the "state" element in it, logically)
I've done a live test and can confirm that the state now comes out in the alarm message.
=> [Reviewer EM] Include alarm state at the end of the alarm OID

.gitignore, Makefile
Fix to my recent PR. I was using the default Python environment for the script, which caused issues on a build system where docopt was not installed in the default environment.
This PR modifies the Makefile to create a virtualenv for the mib generator. Instead of using a `_setup.py` script for setting up the environment, like most of our Python packages, I felt it more appropriate to go with the simpler approach here - those setup scripts are aimed at installable Python packages, rather than a script executed at build time, and the only non-default package we need is docopt. I also only included `envclean` and not `pyclean`, as we don't generate any eggs, compiled Python code, or Python coverage reports.
=> [Reviewer: CNE] Automated mib build infra fix

Makefile, mib-generator/cw_mib_generator.py
@chris-elford-metaswitch could you review today if possible? If not, please reassign and let me know.
Small addition to cw_mib_generator.py to add argument specifying MIB output directory, as suggested by @richardwhiuk. Amends both script, and the Makefile to supply the output directory. This simplifies our build processes as it reduces the amount of copying around; we generate the MIB(s) directly where we want them.
In addition:
* I've moved the PC MIB generation into the if/else block for the `cwc-mib-dir` argument. Logic behind this is that I couldn't think of a scenario where we'd want to generate both at once. Please push back if you disagree here.
* Bunch of variable names changed to add clarity.
=> [Reviewer: CNE] Add output directory argument to MIB generator

mib-generator/cw_mib_generator.py
As you suggested, this increases our smilint verification level to 6. This should now catch all warnings, as well as errors.
Tested against the auto-generated PROJECT-CLEARWATER-MIB, which still passes. I then intentionally made a change that would generate a level 4 error, and it was correctly identified and rejected by smilint, which does not do so without this change.
=> [Reviewer: EM] Increase smilint verification level to 6

mib-generator/INET-ADDRESS-MIB, mib-generator/SNMPv2-CONF, mib-generator/SNMPv2-SMI, mib-generator/SNMPv2-TC, mib-generator/cw_mib_generator.py, mib-generator/smilint.conf
George,
Currently, it's not possible to build clearwater-snmp-handlers, without manually getting the required MIBs, which is a fair pain.
Instead, this checks in the required MIBs, and points smilint to use them.
We'll need to acknowledge the MIB separately.
=> [Reviewer: George] Add the required MIBs to run smilint succesfully

debian/control
Seb,
As discussed, showing the active alarms (using cw-show_active_alarms) requires the SNMP package.
You've tested that this works by manually installing snmp.
=> [Reviewer: Seb] show_active_alarms requires the SNMP package

mib-generator/CLEARWATER-MIB-COMMON
This just changes the name of the homesteadCacheLatencyTable to homesteadHsProvLatencyTable as that's now what it tracks (since it tracks the Cassandra latency)
As discussed, we don't currently have Astaire latency stats, so we're not adding homestead cache latency stats as part of this work
=> [Reviewer: Richard] Cassandra to memcached

src/Makefile
Seb,
Simple fix - same as Astaire - Metaswitch/cpp-common#680 adds a requirement on linking to boost_regex.
=> [Reviewer: Seb] Fix Boost Regex Linker Error

clearwater-snmp-alarm-agent.root/usr/share/clearwater/bin/clearwater-snmp-alarm-agent-wrapper, debian/clearwater-snmp-alarm-agent.upstart
Hi Richard
Can you check that you're happy with this upstart change (and another in clearwater-infrastructure which I'll link).  This stems from a scary instance I've seen of an OOM killer wiping out the top level alarm agent wrapper process, with the result that upstart brought up a new copy of it, even though the cw_alarm_agent process (a grandchild of the original wrapper process) was still running, so we ended up with two alarm agents running.
I've tested that upstart operations (restart, stop, start etc) work as before, with the bonus that if the wrapper process is killed manually, we now get rid of the grandchild.
Note that I think the clearwater-infrastructure instances are the only other ones I could come up with.  The other clearwater-* upstart jobs exec their targets directly …
=> [Reviewer RJW2] Ensure wrapper death doesn't result in duplicate alarm agent processes

mib-generator/CLEARWATER-MIB-COMMON
Adds a stat for the size of the memcached thread pool queue on Homestead.
Counterpart to https://github.com/Metaswitch/homestead/pull/497
I've not yet updated readthedocs, but I'll do that while you're reviewing this PR.
=> [Reviewer: Richard] Homestead memcached stats

Makefile
Adam,
Just noticed the debug package was missing from `Makefile`, and hence from our repo.  Fix is trivial, and safe.
Having said that, we should hold off merging this until branches are cut next week.
Matt
=> [Reviewer: Adam] Add clearwater-snmp-alarm-agent-dbg to Makefile, so it gets included in repo

src/ut/alarm_req_listener_test.cpp, src/ut/mock_alarm_scheduler.h
This fixes the follow-on UT issue in https://github.com/Metaswitch/clearwater-issues/issues/2655.
I looked at whether we could rearrange initialization, but superclass constructors always happen before any member, so I just pulled constructing the lock out of MockAlarmScheduler.
=> [Reviewer: Richard] Fix UT race condition

METASWITCH-OS-MIB
This fixes the bugs we discussed with the ASN.1 file where the tree had an extra element and had some invalid references.
Live tested querying the three entries by name.
Note that I've changed to Integer32. I can't used unsigned integer because the bash handler option doesn't support that, only integer, gauge, counter, timeticks, ipaddress, objectid, or string.
=> Fix up Metaswitch OS MIB
